# Generated by Django 5.2 on 2025-04-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
