# Generated by Django 5.2 on 2025-04-23 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_book_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('POPULARITE', 'Livres les plus populaires'), ('RETARDS', 'Retards fréquents'), ('HISTORIQUE', 'Historique utilisateur')], max_length=20)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('contenu', models.JSONField()),
                ('genere_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
