# Generated by Django 5.2 on 2025-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('roman', 'Roman'), ('poesie', 'Poésie'), ('science', 'Science'), ('informatique', 'Informatique'), ('histoire', 'Histoire'), ('biographie', 'Biographie'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
